### ISSUE TITLE
num_agents in ct_settings

### ISSUE THREAD

**Issue by emailweixu** [idlrl/flare#48]
In many examples, there is num_agents in ct_settings like this
```python
ct_settings = {
    "RL": dict(
        algorithm=alg,       ## pass in the algorithm object
        # sampling
        agent_helper=OnlineHelper,   ## the training data collection is online
        # each agent will call `learn()` every `sample_interval` steps
        sample_interval=4,
        num_agents=num_agents)
}
```
But I cannot find where num_agents is used by the framework. And I actually get an error like this:
Traceback (most recent call last):
  File "rl.py", line 147, in <module>
    manager = Manager(ct_settings, log_settings=dict(print_interval=10, ))
  File "/home/weixu/code/flare/flare/framework/manager.py", line 64, in add_agents
    self.add_agent(agent)
  File "/home/weixu/code/flare/flare/framework/manager.py", line 75, in add_agent
    cdp.create_agent_helper(agent.id),
  File "/home/weixu/code/flare/flare/framework/computation_data_processor.py", line 63, in create_agent_helper
    return self.helper_creator(comm)
  File "/home/weixu/code/flare/flare/framework/computation_data_processor.py", line 20, in <lambda>
    self.helper_creator = (lambda comm: agent_helper(name, comm, **kwargs))
TypeError: __init__() got an unexpected keyword argument 'num_agents'

**Comment by skylian** [comment]
`num_agents` is removed by pr #47 and I believe it is no longer needed.

**Comment by emailweixu** [comment]
So it should be removed from all the examples and tutorials. Otherwise the code cannot run.

**Comment by yu239** [comment]
Yeah some examples are outdated regarding APIs. The one that is guaranteed to run successfully is examples/img_ac_example.py
